# Generated by Django 5.1.1 on 2024-10-23 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_department_batch_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course_name',
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='myapp.department'),
            preserve_default=False,
        ),
    ]
