# Generated by Django 5.1.1 on 2024-10-23 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_batch_name_batch_end_year_batch_start_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='start_year',
        ),
    ]
