# Generated by Django 5.1.1 on 2024-10-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_batch_end_year_batch_start_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='end_year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='batch',
            name='start_year',
            field=models.PositiveIntegerField(),
        ),
    ]
