# Generated by Django 5.1.1 on 2024-10-27 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='department',
        ),
    ]
